// Reproducible given-names generator.
//
// Emits src/data/given-names.generated.ts from AUTHORITATIVE, frequency-ranked
// sources — never hand-typed. Run: `npm run build:names`.
//
// SSA (US): US Social Security Administration popular baby names, consumed via
//   the aruljohn/popular-baby-names mirror (Rank,Name CSV per year/gender).
//   We keep names that reached a top rank in any recent year — "top-N popular".
//
// ONS (UK): the Office for National Statistics publishes "Baby names in England
//   and Wales" (Open Government Licence). It is only distributed as XLSX, not a
//   stable machine-readable CSV, so it is NOT auto-fetched here. To merge it,
//   export the ONS boys/girls sheets to a two-column `rank,name` CSV and pass:
//     ONS_CSV=/path/to/ons.csv npm run build:names
//   The US SSA pool already covers the large shared Anglophone name set; ONS
//   mainly adds UK-distinct popular names.
//
// Precision note: a bigger gazetteer trades precision for recall (see the
// de-id literature: name detection tends to cap ~75-80% precision). The
// RANK_CUTOFF keeps this to *popular* names; the recognizer adds further
// precision guards (ambiguous-name and place/institution stoplists).

import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const YEARS = [2018, 2019, 2020, 2021, 2022];
const RANK_CUTOFF = Number(process.env.RANK_CUTOFF ?? 600); // keep names reaching this rank in any year
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data', 'given-names.generated.ts');

const UA = { headers: { 'User-Agent': 'phi-leak-guard-build/0.0' } };
const ssaUrl = (year, gender) =>
  `https://raw.githubusercontent.com/aruljohn/popular-baby-names/master/${year}/${gender}_names_${year}.csv`;

/** name -> best (lowest) rank seen. */
const bestRank = new Map();
const note = (name, rank) => {
  const k = name.toLowerCase();
  if (!k || !/^[a-z][a-z'’-]*$/.test(k)) return;
  const prev = bestRank.get(k);
  if (prev === undefined || rank < prev) bestRank.set(k, rank);
};

async function fetchSsa() {
  let files = 0;
  for (const year of YEARS) {
    for (const gender of ['boy', 'girl']) {
      try {
        const res = await fetch(ssaUrl(year, gender), UA);
        if (!res.ok) { console.warn(`  SSA ${year} ${gender}: HTTP ${res.status} — skipped`); continue; }
        const csv = await res.text();
        for (const line of csv.split('\n').slice(1)) {
          const [rank, name] = line.split(',');
          if (rank && name) note(name.trim(), Number(rank.trim()));
        }
        files++;
      } catch (e) {
        console.warn(`  SSA ${year} ${gender}: ${e.message} — skipped`);
      }
    }
  }
  return files;
}

async function fetchOnsFromCsv(path) {
  const csv = await readFile(path, 'utf8');
  let n = 0;
  for (const line of csv.split('\n')) {
    const [rank, name] = line.split(',');
    if (rank && name && /^\d+$/.test(rank.trim())) { note(name.trim(), Number(rank.trim())); n++; }
  }
  return n;
}

console.log(`Fetching SSA ranked names for ${YEARS.join(', ')} ...`);
const ssaFiles = await fetchSsa();
if (ssaFiles === 0) {
  console.error('No SSA files fetched — aborting so we do not overwrite good data with nothing.');
  process.exit(1);
}

let onsStatus = 'not merged (no ONS_CSV provided)';
if (process.env.ONS_CSV) {
  const n = await fetchOnsFromCsv(process.env.ONS_CSV);
  onsStatus = `merged ${n} rows from ${process.env.ONS_CSV}`;
  console.log(`ONS: ${onsStatus}`);
}

const names = [...bestRank.entries()]
  .filter(([, r]) => r <= RANK_CUTOFF)
  .map(([n]) => n)
  .sort();

const header = `// AUTO-GENERATED by scripts/build-names.mjs — DO NOT EDIT BY HAND.
// Regenerate: npm run build:names
//
// Source: US SSA popular baby names via aruljohn/popular-baby-names,
//   years ${YEARS.join('/')}, names reaching rank <= ${RANK_CUTOFF} in any year.
// ONS (UK): ${onsStatus}.
// Count: ${names.length} given names. Generated ${new Date().toISOString().slice(0, 10)}.
`;

const body = `export const GIVEN_NAMES: ReadonlySet<string> = new Set([\n${
  names.map((n) => `  ${JSON.stringify(n)},`).join('\n')
}\n]);\n`;

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, `${header}\n${body}`);
console.log(`Wrote ${names.length} names -> ${OUT}`);
